from django.urls import path
from .views import (
    current_user_view,
    login_view,
    logout_all_view,
    logout_view,
    register_view,
    predict_view,
    upload_dataset_view,
    train_view,
    train_status_view,
    models_list_view,
    models_activate_view,
    models_download_view,
    patients_list_view,
    patients_search_view,
    prediction_history_view,
)

urlpatterns = [
    path("auth/login", login_view, name="api_login"),
    path("auth/register", register_view, name="api_register"),
    path("auth/logout", logout_view, name="api_logout"),
    path("auth/logout-all", logout_all_view, name="api_logout_all"),
    path("auth/me", current_user_view, name="api_current_user"),
    path("predict", predict_view, name="api_predict"),
    path("prediction-history", prediction_history_view, name="api_prediction_history"),
    path("patients", patients_list_view, name="api_patients"),
    path("patients/search", patients_search_view, name="api_patients_search"),
    path("upload-dataset", upload_dataset_view, name="api_upload_dataset"),
    path("train", train_view, name="api_train"),
    path("train/status/<str:job_id>", train_status_view, name="api_train_status"),
    path("models", models_list_view, name="api_models"),
    path("models/activate", models_activate_view, name="api_models_activate"),
    path("models/download", models_download_view, name="api_models_download"),
]
