from django.urls import path
from .views import (
    current_user_view,
    login_view,
    logout_all_view,
    logout_view,
    profile_update_view,
    register_view,
    fhir_capability_statement_view,
    fhir_observation_view,
    fhir_patient_view,
    fhir_risk_assessment_view,
    maintenance_api_status_view,
    maintenance_backup_database_view,
    maintenance_clear_temp_files_view,
    maintenance_database_status_view,
    maintenance_export_logs_view,
    maintenance_health_view,
    maintenance_model_status_view,
    maintenance_reload_model_view,
    maintenance_reset_failed_jobs_view,
    maintenance_storage_status_view,
    maintenance_test_prediction_view,
    predict_dataset_view,
    predict_view,
    upload_dataset_view,
    train_view,
    train_status_view,
    training_jobs_view,
    upload_prediction_dataset_view,
    models_list_view,
    models_activate_view,
    models_download_view,
    patients_list_view,
    patients_search_view,
    prediction_history_view,
)

urlpatterns = [
    path("auth/login", login_view, name="api_login"),
    path("auth/register", register_view, name="api_register"),
    path("auth/logout", logout_view, name="api_logout"),
    path("auth/logout-all", logout_all_view, name="api_logout_all"),
    path("auth/me", current_user_view, name="api_current_user"),
    path("auth/profile", profile_update_view, name="api_profile_update"),
    path("predict", predict_view, name="api_predict"),
    path("predict-dataset", predict_dataset_view, name="api_predict_dataset"),
    path("prediction-history", prediction_history_view, name="api_prediction_history"),
    path("patients", patients_list_view, name="api_patients"),
    path("patients/search", patients_search_view, name="api_patients_search"),
    path("api/v1/predictions/run", predict_view, name="api_v1_predict"),
    path("api/v1/predictions", prediction_history_view, name="api_v1_prediction_history"),
    path("api/v1/patients", patients_list_view, name="api_v1_patients"),
    path("api/v1/patients/search", patients_search_view, name="api_v1_patients_search"),
    path("fhir/metadata", fhir_capability_statement_view, name="fhir_metadata"),
    path("fhir/Patient", fhir_patient_view, name="fhir_patient_search"),
    path("fhir/Patient/<str:patient_id>", fhir_patient_view, name="fhir_patient_read"),
    path("fhir/Observation", fhir_observation_view, name="fhir_observation_search"),
    path("fhir/RiskAssessment", fhir_risk_assessment_view, name="fhir_risk_assessment_search"),
    path("fhir/RiskAssessment/<str:prediction_id>", fhir_risk_assessment_view, name="fhir_risk_assessment_read"),
    path("api/admin/maintenance/health/", maintenance_health_view, name="api_admin_maintenance_health"),
    path("api/admin/maintenance/api-status/", maintenance_api_status_view, name="api_admin_maintenance_api_status"),
    path("api/admin/maintenance/database-status/", maintenance_database_status_view, name="api_admin_maintenance_database_status"),
    path("api/admin/maintenance/model-status/", maintenance_model_status_view, name="api_admin_maintenance_model_status"),
    path("api/admin/maintenance/storage-status/", maintenance_storage_status_view, name="api_admin_maintenance_storage_status"),
    path("api/admin/maintenance/reload-model/", maintenance_reload_model_view, name="api_admin_maintenance_reload_model"),
    path("api/admin/maintenance/clear-temp-files/", maintenance_clear_temp_files_view, name="api_admin_maintenance_clear_temp_files"),
    path("api/admin/maintenance/export-logs/", maintenance_export_logs_view, name="api_admin_maintenance_export_logs"),
    path("api/admin/maintenance/reset-failed-jobs/", maintenance_reset_failed_jobs_view, name="api_admin_maintenance_reset_failed_jobs"),
    path("api/admin/maintenance/backup-database/", maintenance_backup_database_view, name="api_admin_maintenance_backup_database"),
    path("api/admin/maintenance/test-prediction/", maintenance_test_prediction_view, name="api_admin_maintenance_test_prediction"),
    path("upload-dataset", upload_dataset_view, name="api_upload_dataset"),
    path("upload-prediction-dataset", upload_prediction_dataset_view, name="api_upload_prediction_dataset"),
    path("train", train_view, name="api_train"),
    path("train/jobs", training_jobs_view, name="api_training_jobs"),
    path("train/status/<str:job_id>", train_status_view, name="api_train_status"),
    path("models", models_list_view, name="api_models"),
    path("models/activate", models_activate_view, name="api_models_activate"),
    path("models/download", models_download_view, name="api_models_download"),
]
